### ISSUE TITLE
INNER JOIN adaptation

### ISSUE THREAD

**Issue by SBS-BAC** [owertz/sql_tools#5]
INNER - Wrong position :

SELECT
    T1.datcrt,
    T1.datmaj,
    T1.heumaj,
    T1.usrmaj,
    T1.pgmmaj,
    T1.refopn,
    T1.staopn,
    T1.numcar_int,
    T1.codges,
    Z1.libel1_1,
    T1.codopn,
    T3.libopn_1,
    T1.codzon,
    T2.libzon_1,
    T1.datopn,
    T1.valatt_car_new,
    T1.valatt_car_old
FROM
    T1 **inner**
JOIN Z1 ON T1.codges = Z1.argtbl
    **inner**
JOIN T3 ON T1.codopn = T3.codopn
    AND T1.codges = T3.codges
    AND T1.codzon = T3.codzon
    **inner**
JOIN T2 ON T1.codzon = T2.codzon
    AND T1.codges = T2.codges
WHERE
    T1.numcar_int = 'xxxxxx'
;

**Comment by owertz** [comment]
Good Afternoon  Célien. 

Thanks for having reported this issue. I've fixed it and deployed a new version. 

Br,
Olivier
